### ISSUE TITLE
README

### ISSUE THREAD

**Issue by Karyum** [FACN3/rikaz#11]
this must be the first thing that goes into a project, before everything. a README. think of it as a country's independence document :sweat_smile: its very important:

here are some examples of READMEs from all around:
 https://github.com/FACN3/easyRep
https://github.com/InFact-coop/LWC

**Comment by Karyum** [comment]
@ghassanmas @prodionov @hasansaad1 This PR was reverted cause @ghassanmas decided to merge his own PR without anyones review even the QA

**Comment by Karyum** [comment]
check my comment here #13

**Comment by ghassanmas** [comment]
you are overreacting, it's just the readme, please check the repos you have referenced above, was there even a PR when the readme was updated?

**Comment by Karyum** [comment]
@ghassanmas i didn't show you the 2 projects so you could check their PRs cause for the first one there is a big comment from me saying that they should have split the pull request and for the second one they split the README into **multiple issues** more than that for each part of the README they contacted their PO. its not just the README as you said before an HR person comes to your project what is the first thing his going to look at ? hmmm let me guess, oh yes it's the README

**Comment by ghassanmas** [comment]
Thats why I updated the readme as soon as possible. Again it's common to update the readme directly without even making a PR

**Comment by Karyum** [comment]
@ghassanmas it's not common, actually it's not even a thing, even worse without your teammate's (@prodionov @hasansaad1 ) approval and a QA's approval. who is going to care about your code if they don't understand whats the point of the project through a good README ??

**Comment by ghassanmas** [comment]
Who's going to care about my code ? There was no code in the readme...

**Comment by ghassanmas** [comment]
![rikaz](https://user-images.githubusercontent.com/16361375/36074262-59a3d660-0f46-11e8-9f57-43978cb4ba3c.png)

**Comment by matthewdking** [comment]
@Karyum closing due to merge
