### ISSUE TITLE
chart 1 (introduction chart)

### ISSUE THREAD

**Issue by prodionov** [FACN3/rikaz#8]
The introduction chart has to include the top level information about smoking. 
- [x] Arab population is represented by 100  (exact number to be discussed) figures (male and female). 
NotaBene: acc to Rikaz (2015), Arab population is 1,392,100, 705,300 males and 686,800 females (51% and 49%, respectively). 

the chart shows:
- [x]  percent ratio of men and women who smokes
- [x]  three filters ( can be applied to the chart: age, education and income ) 
- [x]  the exact ratios have to be displayed on the right in bubles #31

**Comment by hasansaad1** [comment]
how long is this going to take us
how are we building this?
how will we feed the data?
